//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloriesProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Dish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dish()
        {
            this.DishProducts = new HashSet<DishProduct>();
        }

        [DisplayName("Название")]
        public string DishName { get; set; }
        public int DishID { get; set; }
        [DisplayName("Описание")]
        public string DishDescription { get; set; }
        [DisplayName("Калории")]
        public Nullable<double> Calories { get; set; }
        [DisplayName("Белки")]
        public Nullable<double> Proteins { get; set; }
        [DisplayName("Жиры")]
        public Nullable<double> Fats { get; set; }
        [DisplayName("Углеводы")]
        public Nullable<double> Carbohydrates { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DishProduct> DishProducts { get; set; }
        public virtual User User { get; set; }
    }
}
